name: CI

on:
  push:
    branches: [ master, aosen-master ]
  pull_request:
    branches: [ master, aosen-master ]

jobs:
  build:
    strategy:
      matrix:
        jdk: [ 11, 8, 17, 21]
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - name: Pull Request Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
        if: github.head_ref != ''
      - name: Push Checkout
        uses: actions/checkout@v4
        if: github.head_ref == ''
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.jdk}}
          distribution: 'temurin'
      - name: Build
        id: build
        run: ./.ci-build-without-test.sh

      - name: PICO Typecheck Test
        if: ${{ steps.build.outcome == 'success' }}
        run: ./gradlew ImmutabilityTypecheckTest

      - name: PICO Typecheck AllSystems Test
        if: ${{ steps.build.outcome == 'success' }}
        run: ./gradlew ImmutabilityTypecheckBaseAllSystemsTest

      - name: PICO Typecheck Extended Test
        if: ${{ steps.build.outcome == 'success' }}
        run: ./gradlew ImmutabilityTypecheckExtendedTest

#      - name: PICO Inference Initial Typecheck Test
#        if: ${{ steps.build.outcome == 'success' }}
#        run: ./gradlew ImmutabilityInferenceInitialTypecheckTest
#
#      - name: PICO Inference Test
#        if: ${{ steps.build.outcome == 'success' }}
#        run: ./gradlew ImmutabilityInferenceTest
